# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a474b60f6f29dea76d25b6a26360ca3e7cd9b6731bae0850c1a6fcb8f55bb6e5342dbffc31c756cb630315ba144d2ab382df41a5bc6bb88e0dc58d8fcc46160b

test:
  secret_key_base: f149cc7c4172762db9cd02635e97f46b6b9b7ff92f97c9fa67035516c681bea10f4d34eea8e9704ddf2fe5cb59c19ddd54c0b64be12e908bf4f2d13a3cfe410c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
